from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS `api` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `path` VARCHAR(100) NOT NULL  COMMENT 'API路径',
    `method` VARCHAR(6) NOT NULL  COMMENT '请求方法',
    `summary` VARCHAR(500) NOT NULL  COMMENT '请求简介',
    `tags` VARCHAR(100) NOT NULL  COMMENT 'API标签',
    KEY `idx_api_created_78d19f` (`created_at`),
    KEY `idx_api_updated_643c8b` (`updated_at`),
    KEY `idx_api_path_9ed611` (`path`),
    KEY `idx_api_method_a46dfb` (`method`),
    KEY `idx_api_summary_400f73` (`summary`),
    KEY `idx_api_tags_04ae27` (`tags`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `auditlog` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `user_id` INT NOT NULL  COMMENT '用户ID',
    `username` VARCHAR(64) NOT NULL  COMMENT '用户名称' DEFAULT '',
    `module` VARCHAR(64) NOT NULL  COMMENT '功能模块' DEFAULT '',
    `summary` VARCHAR(128) NOT NULL  COMMENT '请求描述' DEFAULT '',
    `method` VARCHAR(10) NOT NULL  COMMENT '请求方法' DEFAULT '',
    `path` VARCHAR(255) NOT NULL  COMMENT '请求路径' DEFAULT '',
    `status` INT NOT NULL  COMMENT '状态码' DEFAULT -1,
    `response_time` INT NOT NULL  COMMENT '响应时间(单位ms)' DEFAULT 0,
    `request_args` JSON   COMMENT '请求参数',
    `response_body` JSON   COMMENT '返回数据',
    KEY `idx_auditlog_created_cc33d0` (`created_at`),
    KEY `idx_auditlog_updated_2f871f` (`updated_at`),
    KEY `idx_auditlog_user_id_4b93fa` (`user_id`),
    KEY `idx_auditlog_usernam_b187b3` (`username`),
    KEY `idx_auditlog_module_04058b` (`module`),
    KEY `idx_auditlog_summary_3e27da` (`summary`),
    KEY `idx_auditlog_method_4270a2` (`method`),
    KEY `idx_auditlog_path_b99502` (`path`),
    KEY `idx_auditlog_status_2a72d2` (`status`),
    KEY `idx_auditlog_respons_8caa87` (`response_time`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `dept` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL UNIQUE COMMENT '部门名称',
    `desc` VARCHAR(500)   COMMENT '备注',
    `is_deleted` BOOL NOT NULL  COMMENT '软删除标记' DEFAULT 0,
    `order` INT NOT NULL  COMMENT '排序' DEFAULT 0,
    `parent_id` INT NOT NULL  COMMENT '父部门ID' DEFAULT 0,
    KEY `idx_dept_created_4b11cf` (`created_at`),
    KEY `idx_dept_updated_0c0bd1` (`updated_at`),
    KEY `idx_dept_name_c2b9da` (`name`),
    KEY `idx_dept_is_dele_466228` (`is_deleted`),
    KEY `idx_dept_order_ddabe1` (`order`),
    KEY `idx_dept_parent__a71a57` (`parent_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `deptclosure` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `ancestor` INT NOT NULL  COMMENT '父代',
    `descendant` INT NOT NULL  COMMENT '子代',
    `level` INT NOT NULL  COMMENT '深度' DEFAULT 0,
    KEY `idx_deptclosure_created_96f6ef` (`created_at`),
    KEY `idx_deptclosure_updated_41fc08` (`updated_at`),
    KEY `idx_deptclosure_ancesto_fbc4ce` (`ancestor`),
    KEY `idx_deptclosure_descend_2ae8b1` (`descendant`),
    KEY `idx_deptclosure_level_ae16b2` (`level`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `exchange_account` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `email` VARCHAR(255) NOT NULL UNIQUE COMMENT '邮箱地址',
    `username` VARCHAR(100) NOT NULL  COMMENT '登录用户名（不含域名）',
    `encrypted_password` LONGTEXT NOT NULL  COMMENT '加密后的密码',
    `display_name` VARCHAR(100)   COMMENT '显示名称',
    `server` VARCHAR(255)   COMMENT 'Exchange服务器地址',
    `domain` VARCHAR(100)   COMMENT '域名',
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    `is_verified` BOOL NOT NULL  COMMENT '是否已验证连接' DEFAULT 0,
    `last_verified_at` DATETIME(6)   COMMENT '最后验证时间',
    `owner_id` BIGINT NOT NULL  COMMENT '所属用户ID',
    `remark` VARCHAR(500)   COMMENT '备注',
    KEY `idx_exchange_ac_created_78a0f5` (`created_at`),
    KEY `idx_exchange_ac_updated_625e58` (`updated_at`),
    KEY `idx_exchange_ac_email_9340d8` (`email`),
    KEY `idx_exchange_ac_usernam_074238` (`username`),
    KEY `idx_exchange_ac_is_acti_a520bc` (`is_active`),
    KEY `idx_exchange_ac_is_veri_a09d6b` (`is_verified`),
    KEY `idx_exchange_ac_owner_i_73eac2` (`owner_id`)
) CHARACTER SET utf8mb4 COMMENT='邮箱账户模型';
CREATE TABLE IF NOT EXISTS `exchange_api_key` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(100) NOT NULL  COMMENT '密钥名称',
    `key_prefix` VARCHAR(8) NOT NULL  COMMENT '密钥前缀（用于识别）',
    `key_hash` VARCHAR(64) NOT NULL UNIQUE COMMENT '密钥哈希值',
    `permissions` JSON NOT NULL  COMMENT '权限列表',
    `allowed_accounts` JSON NOT NULL  COMMENT '允许使用的账户ID列表',
    `ip_whitelist` JSON NOT NULL  COMMENT 'IP白名单',
    `rate_limit` INT NOT NULL  COMMENT '每分钟请求限制' DEFAULT 100,
    `expires_at` DATETIME(6)   COMMENT '过期时间',
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    `last_used_at` DATETIME(6)   COMMENT '最后使用时间',
    `usage_count` BIGINT NOT NULL  COMMENT '使用次数' DEFAULT 0,
    `owner_id` BIGINT NOT NULL  COMMENT '所属用户ID',
    `remark` VARCHAR(500)   COMMENT '备注',
    KEY `idx_exchange_ap_created_8e0137` (`created_at`),
    KEY `idx_exchange_ap_updated_2bf8c9` (`updated_at`),
    KEY `idx_exchange_ap_name_2adf53` (`name`),
    KEY `idx_exchange_ap_key_pre_569e92` (`key_prefix`),
    KEY `idx_exchange_ap_key_has_48bbaa` (`key_hash`),
    KEY `idx_exchange_ap_expires_b416fd` (`expires_at`),
    KEY `idx_exchange_ap_is_acti_4a69a6` (`is_active`),
    KEY `idx_exchange_ap_owner_i_3a4993` (`owner_id`)
) CHARACTER SET utf8mb4 COMMENT='API 密钥模型';
CREATE TABLE IF NOT EXISTS `exchange_audit_log` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `operator_id` BIGINT NOT NULL  COMMENT '操作者用户ID',
    `operator_name` VARCHAR(100)   COMMENT '操作者用户名',
    `action` VARCHAR(50) NOT NULL  COMMENT '操作类型',
    `resource_type` VARCHAR(50) NOT NULL  COMMENT '资源类型',
    `resource_id` BIGINT   COMMENT '资源ID',
    `resource_name` VARCHAR(255)   COMMENT '资源名称/标识',
    `details` JSON   COMMENT '操作详情（变更前后对比等）',
    `request_ip` VARCHAR(50)   COMMENT '请求IP',
    `user_agent` VARCHAR(500)   COMMENT 'User-Agent',
    `status` VARCHAR(20) NOT NULL  COMMENT '操作状态' DEFAULT 'success',
    `error_message` LONGTEXT   COMMENT '错误信息',
    KEY `idx_exchange_au_created_eef999` (`created_at`),
    KEY `idx_exchange_au_updated_90b96f` (`updated_at`),
    KEY `idx_exchange_au_operato_1665b5` (`operator_id`),
    KEY `idx_exchange_au_action_cb7168` (`action`),
    KEY `idx_exchange_au_resourc_9d68af` (`resource_type`),
    KEY `idx_exchange_au_resourc_961c59` (`resource_id`)
) CHARACTER SET utf8mb4 COMMENT='管理操作审计日志模型';
CREATE TABLE IF NOT EXISTS `exchange_email_template` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(100) NOT NULL  COMMENT '模板名称',
    `subject` VARCHAR(500) NOT NULL  COMMENT '邮件主题',
    `body` LONGTEXT NOT NULL  COMMENT '邮件正文',
    `body_type` VARCHAR(10) NOT NULL  COMMENT '正文类型: text/html' DEFAULT 'html',
    `category` VARCHAR(50)   COMMENT '分类标签',
    `variables` JSON NOT NULL  COMMENT '变量列表',
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    `owner_id` BIGINT NOT NULL  COMMENT '所属用户ID',
    `remark` VARCHAR(500)   COMMENT '备注',
    KEY `idx_exchange_em_created_238dcd` (`created_at`),
    KEY `idx_exchange_em_updated_ef6368` (`updated_at`),
    KEY `idx_exchange_em_name_4b8741` (`name`),
    KEY `idx_exchange_em_categor_8a86a5` (`category`),
    KEY `idx_exchange_em_is_acti_37e74a` (`is_active`),
    KEY `idx_exchange_em_owner_i_cccc24` (`owner_id`)
) CHARACTER SET utf8mb4 COMMENT='邮件模板模型';
CREATE TABLE IF NOT EXISTS `exchange_mail_log` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `api_key_id` BIGINT   COMMENT '使用的API密钥ID',
    `account_id` BIGINT NOT NULL  COMMENT '使用的邮箱账户ID',
    `action` VARCHAR(20) NOT NULL  COMMENT '操作类型',
    `recipients` JSON   COMMENT '收件人列表',
    `cc_recipients` JSON   COMMENT '抄送列表',
    `bcc_recipients` JSON   COMMENT '密送列表',
    `subject` VARCHAR(500)   COMMENT '邮件主题',
    `has_attachments` BOOL NOT NULL  COMMENT '是否有附件' DEFAULT 0,
    `status` VARCHAR(20) NOT NULL  COMMENT '状态' DEFAULT 'pending',
    `error_message` LONGTEXT   COMMENT '错误信息',
    `request_ip` VARCHAR(50)   COMMENT '请求IP',
    `request_id` VARCHAR(50)   COMMENT '请求ID',
    KEY `idx_exchange_ma_created_95ce49` (`created_at`),
    KEY `idx_exchange_ma_updated_c83ac8` (`updated_at`),
    KEY `idx_exchange_ma_api_key_ef1039` (`api_key_id`),
    KEY `idx_exchange_ma_account_5376b5` (`account_id`),
    KEY `idx_exchange_ma_action_0a8fc7` (`action`),
    KEY `idx_exchange_ma_status_db58da` (`status`),
    KEY `idx_exchange_ma_request_333c59` (`request_id`)
) CHARACTER SET utf8mb4 COMMENT='邮件操作日志模型';
CREATE TABLE IF NOT EXISTS `lark_app` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(100) NOT NULL  COMMENT '应用名称',
    `app_id` VARCHAR(50) NOT NULL UNIQUE COMMENT 'App ID',
    `encrypted_app_secret` LONGTEXT NOT NULL  COMMENT '加密后的 App Secret',
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    `is_connected` BOOL NOT NULL  COMMENT 'WebSocket 是否已连接' DEFAULT 0,
    `last_connected_at` DATETIME(6)   COMMENT '最后连接时间',
    `owner_id` BIGINT NOT NULL  COMMENT '所属用户ID',
    `remark` VARCHAR(500)   COMMENT '备注',
    KEY `idx_lark_app_created_568cce` (`created_at`),
    KEY `idx_lark_app_updated_1beb1d` (`updated_at`),
    KEY `idx_lark_app_app_id_291b8e` (`app_id`),
    KEY `idx_lark_app_is_acti_bb5d45` (`is_active`),
    KEY `idx_lark_app_owner_i_272e27` (`owner_id`)
) CHARACTER SET utf8mb4 COMMENT='飞书应用配置';
CREATE TABLE IF NOT EXISTS `lark_event_log` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `task_queue_id` BIGINT NOT NULL  COMMENT '任务队列ID',
    `event_id` VARCHAR(100) NOT NULL UNIQUE COMMENT '飞书事件ID',
    `record_id` VARCHAR(100) NOT NULL  COMMENT '多维表格记录ID',
    `action` VARCHAR(50) NOT NULL  COMMENT '操作类型: record_added, record_edited',
    `status` VARCHAR(20) NOT NULL  COMMENT '处理状态' DEFAULT 'pending',
    `mail_log_id` BIGINT   COMMENT '关联的邮件日志ID',
    `subject` VARCHAR(255)   COMMENT '邮件主题',
    `error_message` LONGTEXT   COMMENT '错误信息',
    `raw_event` JSON   COMMENT '原始事件数据',
    KEY `idx_lark_event__created_38ad7f` (`created_at`),
    KEY `idx_lark_event__updated_3a5bd9` (`updated_at`),
    KEY `idx_lark_event__task_qu_20f0d4` (`task_queue_id`),
    KEY `idx_lark_event__event_i_7774df` (`event_id`),
    KEY `idx_lark_event__record__7db8a4` (`record_id`),
    KEY `idx_lark_event__status_24f035` (`status`)
) CHARACTER SET utf8mb4 COMMENT='飞书事件处理日志';
CREATE TABLE IF NOT EXISTS `lark_task_queue` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `owner_id` BIGINT NOT NULL  COMMENT '所属用户ID',
    `name` VARCHAR(100) NOT NULL  COMMENT '订阅名称，如：财务系统邮件队列',
    `bitable_token` VARCHAR(100) NOT NULL  COMMENT '多维表格 App Token',
    `table_id` VARCHAR(100) NOT NULL  COMMENT '任务表 Table ID',
    `field_mapping` JSON NOT NULL  COMMENT '字段映射配置',
    `status_pending` VARCHAR(50) NOT NULL  COMMENT '待处理状态值' DEFAULT '待处理',
    `status_processing` VARCHAR(50) NOT NULL  COMMENT '处理中状态值' DEFAULT '处理中',
    `status_success` VARCHAR(50) NOT NULL  COMMENT '成功状态值' DEFAULT '成功',
    `status_failed` VARCHAR(50) NOT NULL  COMMENT '失败状态值' DEFAULT '失败',
    `default_account_id` BIGINT   COMMENT '默认 Exchange 账户ID',
    `is_subscribed` BOOL NOT NULL  COMMENT '是否已订阅' DEFAULT 0,
    `is_active` BOOL NOT NULL  COMMENT '是否启用' DEFAULT 1,
    `remark` VARCHAR(500)   COMMENT '备注',
    `app_id` BIGINT NOT NULL COMMENT '关联的飞书应用',
    UNIQUE KEY `uid_lark_task_q_bitable_75e4a1` (`bitable_token`, `table_id`),
    CONSTRAINT `fk_lark_tas_lark_app_72099cba` FOREIGN KEY (`app_id`) REFERENCES `lark_app` (`id`) ON DELETE CASCADE,
    KEY `idx_lark_task_q_created_1e851b` (`created_at`),
    KEY `idx_lark_task_q_updated_10711c` (`updated_at`),
    KEY `idx_lark_task_q_owner_i_67d1c9` (`owner_id`),
    KEY `idx_lark_task_q_bitable_db79aa` (`bitable_token`),
    KEY `idx_lark_task_q_is_subs_f9d5bc` (`is_subscribed`),
    KEY `idx_lark_task_q_is_acti_bc6fdd` (`is_active`)
) CHARACTER SET utf8mb4 COMMENT='邮件任务队列订阅配置';
CREATE TABLE IF NOT EXISTS `menu` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL  COMMENT '菜单名称',
    `remark` JSON   COMMENT '保留字段',
    `menu_type` VARCHAR(7)   COMMENT '菜单类型',
    `icon` VARCHAR(100)   COMMENT '菜单图标',
    `path` VARCHAR(100) NOT NULL  COMMENT '菜单路径',
    `order` INT NOT NULL  COMMENT '排序' DEFAULT 0,
    `parent_id` INT NOT NULL  COMMENT '父菜单ID' DEFAULT 0,
    `is_hidden` BOOL NOT NULL  COMMENT '是否隐藏' DEFAULT 0,
    `component` VARCHAR(100) NOT NULL  COMMENT '组件',
    `keepalive` BOOL NOT NULL  COMMENT '存活' DEFAULT 1,
    `redirect` VARCHAR(100)   COMMENT '重定向',
    KEY `idx_menu_created_b6922b` (`created_at`),
    KEY `idx_menu_updated_e6b0a1` (`updated_at`),
    KEY `idx_menu_name_b9b853` (`name`),
    KEY `idx_menu_path_bf95b2` (`path`),
    KEY `idx_menu_order_606068` (`order`),
    KEY `idx_menu_parent__bebd15` (`parent_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `role` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(20) NOT NULL UNIQUE COMMENT '角色名称',
    `desc` VARCHAR(500)   COMMENT '角色描述',
    KEY `idx_role_created_7f5f71` (`created_at`),
    KEY `idx_role_updated_5dd337` (`updated_at`),
    KEY `idx_role_name_e5618b` (`name`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `username` VARCHAR(20) NOT NULL UNIQUE COMMENT '用户名称',
    `alias` VARCHAR(30)   COMMENT '姓名',
    `email` VARCHAR(255) NOT NULL UNIQUE COMMENT '邮箱',
    `phone` VARCHAR(20)   COMMENT '电话',
    `password` VARCHAR(128)   COMMENT '密码',
    `is_active` BOOL NOT NULL  COMMENT '是否激活' DEFAULT 1,
    `is_superuser` BOOL NOT NULL  COMMENT '是否为超级管理员' DEFAULT 0,
    `last_login` DATETIME(6)   COMMENT '最后登录时间',
    `dept_id` INT   COMMENT '部门ID',
    KEY `idx_user_created_b19d59` (`created_at`),
    KEY `idx_user_updated_dfdb43` (`updated_at`),
    KEY `idx_user_usernam_9987ab` (`username`),
    KEY `idx_user_alias_6f9868` (`alias`),
    KEY `idx_user_email_1b4f1c` (`email`),
    KEY `idx_user_phone_4e3ecc` (`phone`),
    KEY `idx_user_is_acti_83722a` (`is_active`),
    KEY `idx_user_is_supe_b8a218` (`is_superuser`),
    KEY `idx_user_last_lo_af118a` (`last_login`),
    KEY `idx_user_dept_id_d4490b` (`dept_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(100) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `role_menu` (
    `role_id` BIGINT NOT NULL,
    `menu_id` BIGINT NOT NULL,
    FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`menu_id`) REFERENCES `menu` (`id`) ON DELETE CASCADE,
    UNIQUE KEY `uidx_role_menu_role_id_90801c` (`role_id`, `menu_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `role_api` (
    `role_id` BIGINT NOT NULL,
    `api_id` BIGINT NOT NULL,
    FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`api_id`) REFERENCES `api` (`id`) ON DELETE CASCADE,
    UNIQUE KEY `uidx_role_api_role_id_ba4286` (`role_id`, `api_id`)
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `user_role` (
    `user_id` BIGINT NOT NULL,
    `role_id` BIGINT NOT NULL,
    FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE,
    UNIQUE KEY `uidx_user_role_user_id_d0bad3` (`user_id`, `role_id`)
) CHARACTER SET utf8mb4;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
